// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhyLfM0mLNEnORAezrKwJk240mykjRLE',
    appId: '1:661058115409:web:5586aa6ca84e9a30546570',
    messagingSenderId: '661058115409',
    projectId: 'dovtron-f9840',
    authDomain: 'dovtron-f9840.firebaseapp.com',
    storageBucket: 'dovtron-f9840.appspot.com',
    measurementId: 'G-LQTTBEHBB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAye3ISsym_xB75cnR7js--W7GAYCCI_IQ',
    appId: '1:661058115409:android:44012e7aef0cf85f546570',
    messagingSenderId: '661058115409',
    projectId: 'dovtron-f9840',
    storageBucket: 'dovtron-f9840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEGOlj065-MsvELwWifCoXXRMiGI7LBp0',
    appId: '1:661058115409:ios:020e95f240b95bc1546570',
    messagingSenderId: '661058115409',
    projectId: 'dovtron-f9840',
    storageBucket: 'dovtron-f9840.appspot.com',
    iosClientId: '661058115409-jsv8udpeh1bkn7oo109pgifcjodbgvsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dovtron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEGOlj065-MsvELwWifCoXXRMiGI7LBp0',
    appId: '1:661058115409:ios:020e95f240b95bc1546570',
    messagingSenderId: '661058115409',
    projectId: 'dovtron-f9840',
    storageBucket: 'dovtron-f9840.appspot.com',
    iosClientId: '661058115409-jsv8udpeh1bkn7oo109pgifcjodbgvsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.dovtron',
  );
}
